import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/shared/header'
import { Footer } from '@/shared/footer'
import { Cairo } from 'next/font/google'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Providers } from '@/lib/context/providers'

const cairo = Cairo({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Fady',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${cairo.className} antialiased`}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
