import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/shared/header'
import { Footer } from '@/shared/footer'
import { Cairo } from 'next/font/google'
import { PostHogProvider } from '@/lib/context/posthog-context'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const cairo = Cairo({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Fady',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={`${cairo.className} antialiased`}>
                <PostHogProvider>
                    <Header />
                    {children}
                    <Footer />
                </PostHogProvider>
            </body>
        </html>
    )
}
